# Generated by Django 6.0 on 2026-03-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField()),
                ('package', models.CharField()),
                ('requests', models.CharField()),
                ('paymentId', models.CharField()),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
