# Generated by Django 6.0 on 2026-03-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
